FROM docker.io/library/rust:1.85-bookworm

WORKDIR /workspace/nixos-dockers
COPY . .

RUN apt-get update \
    && apt-get install --yes --no-install-recommends acl \
    && rm -rf /var/lib/apt/lists/*

RUN cargo test --locked -p container-init-cli --test docker --no-run
CMD ["cargo", "test", "--locked", "-p", "container-init-cli", "--test", "docker", "--", "--test-threads=1", "--nocapture"]
